---
title: "MW_PRODUCTREVIEWS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(here)
library(tidyverse)
library(dplyr)
library(sjlabelled)
library(maps)
library(ggraph)
library(zipcode)
library(tidygraph)
library(sf)
library(albersusa)
library(RMySQL)
```

```{r, cleaning part 1}
data_delete = read.csv("MW-DELETED.csv")
data_delete <- data_delete%>%
  mutate(type = "deleted")
  
data_notpub = read.csv("MW-ALLNOTPUBLISHED.csv")
data_notpub<- data_notpub%>%
  mutate(type= "not published")

data_pub = read.csv("MW-ALLPUBLISHED.csv")
data_pub <- data_pub %>%
  mutate(type="published")
product <- rbind(data_delete,data_notpub,data_pub)

write.csv(product, 'product.csv')

```

```{r, cleaning part 2 w/ gender}
product_clean = read.csv("product.csv")
```

```{r}
data_usecase = read.csv("final_use_case_analysis.csv")
data_gender = read.csv("final_gender_analysis.csv")
data_condition = read.csv("final_condition_analysis.csv")
```
```{r, function walk through}
#input of lyme disease, female, picc line

rank_lyme<- data_condition%>%
  filter(condition == "lyme disease")%>%
  arrange(desc(proportion))

rank_female<- data_gender%>%
  filter(gender == "female")%>%
  arrange(desc(proportion))

rank_piccline<- data_usecase %>%
  filter(use.case == "hold PIIC line")%>%
  arrange(desc(proportion))%>%
  mutate(rank = rank(proportion))

```

